sudo: false
language: java
jdk: oraclejdk8
before_script:
  - npm install -g bower
  - bower install
before_install:
- chmod +x gradlew
install: ./gradlew assemble --refresh-dependencies
cache:
  directories:
  - $HOME/.gradle
deploy:provider: heroku
  buildpack: gradle
  app: ether-camp
  api_key:
    secure: G3kOnoOvzE1luOhSRF98y3ajQb47TmjSowUkveHADgutq77/GzsaTLuF5BD5f5FLTjb81xaRcje3Ky0atLKxaDtN7rC7v+XVjwY4LNEt163Tdq62xh/40fuYzI58lv+qhzLZz5+6SAmPYNCtN2JFfaH4QEXoFUkB77VgfjsTm9JhA64NStz63pAPFohzegqb3L/l/nowJhowJ20Zc00v0KIrrwyLQzz62EpZKEnsh2u7ORXf9xhc9U9BID8ut35FgaHlIZFIFOstPoOKFOYNsbJlHaeoWQiq/OgHicxY6nX7NLhz8PSShm40acKk85ZaRKggzo054Tz9/kwe0U4RL9FFvde+nXF1T9L2gUBzq5mdP+2dKfYYoLhOo5PxraL+z7G8TZrCO2kWYa0O3r0c/pQAs4a+fAIgoDRwHaU/JgfFXTLErjW/M+tSykj9ENJNhccCif3EM1uX3Qb5EsHBuWUMIcykhaP0PJCjMFoX5pfPv1Vlvpeg4W6Ascc7Ngoh6+0rjZm4KEVpLvSC1X68mN6ardWmQkSj4JHvrPQajZgFtMx63cL2ouDdQOjnq9HVB3OZzFiho2BGbalYxFNx/5zkoGvukdp0G5FUSxn4z3tZAVnsQE4VY6oJi3jI2QS2K/Auco9AavBLmf63Iuck0emPOb5ASCBuS7Lk9/rzZCI=
