sudo: false
language: java
jdk: oraclejdk8
before_script:
  - npm install -g bower
  - bower install
before_install:
- chmod +x gradlew
install: ./gradlew assemble --refresh-dependencies
cache:
  directories:
  - $HOME/.gradle
deploy:
  provider: heroku
  buildpack: gradle
  app: ether-camp
  api_key:
    secure: qv8Wq9hhT138CrDyzQMwZq4Iyic3tmvq14DwB9bLy7aDB0DWwaYX+MAR14qZP2RhOVcOb6KW+8DH+E+dP/DeI8o/1mOVVojg2+Qsdypt9v8h0YLMqHWHcoTw03rlNkx0mXyR53wQNBHfSFX/J6J+k4AvZAOKh42es83geNP5r9CY8A+puLh+1/D/uHBDxZJ3ODRR/5E0/UHIsgVNrKls3HEw36FayVXCTm/slfUOu1sJ13lOpEgD7SLALLGW8nIRwfYuviJvgeZLjmIh6+N7Z8U8H11OSA/EOTnDqVlPDv6eV7X/qP76RzRUSlFj89LTA0sDvJ2EpJDU3CBBSkTYQNO8nHtX2ZEvQSnVS9T7VOWsy93tk48h2TbZgPVqnjVqjyZ+KvAUnZ1yqb2oTcTTAigpHWQINs07N+4ZtyVoyxkR8c8LlQctgEiHm7k2r8eVZxo8pF5GKdRTsBR/QmYr9t8BkO9TXPaXkNXEkNgDVoT/ccUgxqKzLorx2ycdAOf7DvMgAEScnzmpTxnTpPGVrj1EAwt8IgMLk12auPfMRlSLlBGNm/0kgdtz6K5nKk7kMF8xXt5GSEE8ZHSwpyZl+MEOQXz2NLJeHn0RxODKaoOEfUWmZOYk0BkfCeRyNIYIy3JY3CCRLzQHZlzeQGELzN7KMXuaByJowdvzaChv1Hw=